sonar.projectKey=Bayly-AI_AgentGraph2
sonar.organization=bayly-ai
sonar.projectName=AgentGraph
sonar.sources=agentgraph
sonar.tests=tests
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.pytest_cache/**,**/release/**,**/docs/**,**/packages/**,.github/**
sonar.cpd.exclusions=**
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
